algoritmo "semnome"
// Função :
// Autor :
// Data : 16/09/2017
// Seção de Declarações
var
contador:inteiro
resultado:real
somaContador:real
inicio
contador<-1

enquanto contador <= 5 faca
   resultado <- resultado + contador
   escreval(somaContador," + ", contador," =", resultado)
   somaContador <-resultado
   contador <- contador + 1
fimenquanto
escreval("o resultado he", resultado)
fimalgoritmo
